### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by Paolo-Serra** [r0075h3ll/Oralyzer#14]
Hey man!

I tried to use your tool, but i got this error:

```
[92m   ____           __
  / __ \_______ _/ /_ _____ ___ ____
 / /_/ / __/ _ `/ / // /_ // -_) __/
 \____/_/  \_,_/_/\_, //__/\__/_/
                 /___/
[00m
Traceback (most recent call last):
  File "oralyzer.py", line 50, in <module>
    file = open(FilePath).read().splitlines()
  File "C:\Users\XXXXXX\AppData\Local\Programs\Python\Python37\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 1215: character maps to <undefined>
```
The command (python 3): python oralyzer.py -u https://<target>/it?requestUrl=site.com
Hope you can resolve it!

**Comment by r0075h3ll** [comment]
I've applied a fix, can you check(reclone the repo) and confirm if it's working or not?

**Comment by Paolo-Serra** [comment]
yes, I can confirm it has been fixed.
